# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 6a68.net
email: ohai@6a68.net
description: > # this means to ignore newlines until "baseurl:"
  tech blog // jared hirsch // ¯\_(ツ)_/¯
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://6a68.net" # the base hostname & protocol for your site
twitter_username: 6a68
github_username:  6a68
permalink: /:year/:title/

# Build settings
markdown: kramdown

# yay, Atom
gems:
  - jekyll-feed
